language: python
python:
  - "2.7"
# command to install dependencies
install:
  # Install conda
  - sudo pip install conda
  # install deps
  - sudo conda init
  # sudo conda update conda --yes
  - conda create -p $HOME/py --yes pip numpy scipy "python=$TRAVIS_PYTHON_VERSION"
  - export PATH=$HOME/py/bin:$PATH
  # command to install dependencies
  - pip install unidecode nltk wget
  - pip install -r requirements.txt
  - pip install .
  - python -e "import nltk; nltk.download('punkt'); nltk.download('stopwords');"
# command to run tests
script: 
  - cd demo-data
  - ./get-data.sh
