language: python
python:
  - "2.7"
# command to install dependencies
install:
  # Install conda
  - sudo pip install conda
  # install deps
  - sudo conda init
  - sudo apt-get install libenchant-dev
  # sudo conda update conda --yes
  - conda create -p $HOME/py --yes pip numpy scipy nltk unidecode "python=$TRAVIS_PYTHON_VERSION"
  - export PATH=$HOME/py/bin:$PATH
  # install topic explorer
  - python setup.py install
# command to run tests
script: 
  - vsm demo
